apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: redis

spec:

  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  replicas: 1
  template:

    metadata:
      name: redis
      labels:
        name: redis
        app: demo

    spec:

      containers:

      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: vol
          mountPath: /scrub

      volumes:
        - name: vol
          hostPath:
            path: /root/redis
