apiVersion: v1
kind: Pod

metadata:
  name: web
  labels:
    name: web
    app: demo

spec:
  containers:
  - name: web
    image: "acinwinstack/redis_count:pod"
    env:
    - name: "REDIS_HOST"
      value: "redis_pod_ip"
    - name: "NAME"
      value: "your_name"
    ports:
    - containerPort: 80
